name: End-to-end tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instalar dependências do npm
      - name: Install dependencies
        run: npm install

      # Rodar os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6

      # Armazenar screenshots apenas em falhas
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      # Armazenar vídeos
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
